version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.15.1
      - image: circleci/mysql:5.7
        environment:
          MYSQL_USER: 'root' 
          MYSQL_DATABASE: 'FEC'
          MYSQL_ROOT_PASSWORD: 'AbodelYsF113'
    
    steps:
      - checkout
      - run: npm install 
      - run: npm run build
      - run: npm run seed 
      - run: npm test
